### ISSUE TITLE
Skipping CSV files

### ISSUE THREAD

**Issue by dorianvee** [DrauzJu/gdrive-sync#1]
Firstly, nice app. Works like a charm, except for 1 thing. I've noticed it skips .csv files stored on google drive. I'm assuming because of mime-type? Do you have any thoughts on how to get it syncing csv files?

**Comment by DrauzJu** [comment]
Hi, thanks for using it! 
I just tested it with a normal .csv file, it was downloaded correctly. Maybe it is a Google Spreadsheet? These types of files can not be downloaded, since its a Google-specific format (I just pushed some changes to improve the log message in such a case). Such files can only be exported, which is also possible via the API, but not implemented yet (PRs are welcome :))

**Comment by dorianvee** [comment]
Ahh yes. Drive was converting them to sheets on upload. Settings change resolved that. Thanks!
Exporting would definitely be useful.
